# Run:
#   docker-compose run --rm --service-ports nbserv /root/bin/run-jupyter-notebook.sh
version: '3.5'

services:
    nbserv:
        build: ./nbserv
        volumes:
            - ./notebooks:/notebooks
            - ./nbserv/container-init:/root
            - ./:/app
        ports:
            - 8888:8888
        stdin_open: true
        tty: true
